#!/bin/bash
################################################################
# **Loader Script**
#
# This script autoloads the developer tools into the terminal.
################################################################

#####################
# Developer SDK Path
#####################
DEVSDK="$HOME/git/lib/sdk-cli"

###################################
# Android Developer Tools SDK Path
###################################
export ANDROID_HOME="${HOME}/Library/Android/sdk"
export ANDROID_SDK_ROOT=$ANDROID_HOME

#############################
# Retrieve Global Variables
#############################

if [ -f $DEVSDK/sbin/variables ]; then
	source $DEVSDK/sbin/variables
else
	echo "$(tput setaf 1)Developer Tools: Unable to load global variable$(tput setaf 0)}";
fi

####################################
# Sets Include Path to support:
#
#    1) macports commands
#    2) uh developer tools
#    3) built-in apple commands
#    4) android developer tools
####################################

export PATH=""
declare -a include=(
	"$DEVSDK/bin"
	"/usr/bin"
	"/usr/local/bin"
	"/bin"
	"/usr/sbin"
	"/sbin"
	"$ANDROID_HOME/tools"
	"$ANDROID_HOME/platform-tools"
	"$ANDROID_HOME/emulator"
	"$HOME/Library/Python/2.7/bin"
	"/opt/local/bin"
	"/opt/homebrew/bin"
	"$HOME/.npm-packages/bin"
	"$HOME/.yarn/bin"
	"$HOME/.rbenv/shims"
)

for i in "${include[@]}"
do
   PATH+=":$i"
done

#################################################################
# Retrieves These Custom Bash Sources:
#
#    1) aliases for developing simplicity and efficiency
#	 2) helper functions for developing simplicity and efficiency
#	 3) sentry functions for common long processes
#################################################################


# 2) Aliases
if [ -f $DEVSDK/sbin/aliases ]; then
	source $DEVSDK/sbin/aliases
else
	echo "${RED}Developer SDK: Helper Aliases Missing${WHITE}";
fi

# 3) Helper Functions
if [ -f $DEVSDK/sbin/helpers ]; then
	source $DEVSDK/sbin/helpers
else
	echo "${RED}Developer SDK: Helper Functions Missing${WHITE}";
fi

# 3) Sentry Functions
if [ -f $DEVSDK/sbin/sentry ]; then
	source $DEVSDK/sbin/sentry
else
	echo "${RED}Developer SDK: Sentry Functions Missing${WHITE}";
fi


echo "${WHITE}Developer SDK Loaded ${WHITE}";


#######################
# Set Profile Styling
#######################
setopt PROMPT_SUBST
PROMPT='%F{red}%n%f%F{white}@%f%F{cyan}%m%f %F{yellow}[%W]%f %F{white}%~%f%F{green}$(git_prompt)%f$ '


########################
# **END Loader Script**
########################
