#!/bin/bash
########################################################################
# **Helper Functions Script**
#
# This script contains reusable functions designed for performing common
# tasks more efficient and condensing long commands for simplicity.
########################################################################


################################
# Toggle Hidden Files in Finder
################################
function hidden {
    if ! ( [ $1 ])	then
		echo -e "${RED}Missing Argument: [on|off]${WHITE}"
		return
    fi
    case "$1" in
		on)
		  defaults write com.apple.finder AppleShowAllFiles YES;
		  killall Finder;
		  echo -e "${BLUE}Hidden Files On${WHITE}";
		  ;;
		off)
		  defaults write com.apple.finder AppleShowAllFiles NO;
		  killall Finder;
		  echo -e "${BLUE}Hidden Files Off${WHITE}";
		  ;;
		*)
	  echo -e "${RED}Invalid Argument: [on|off]${WHITE}"
	  return
	  ;;
    esac
}

############################
# Destroy Certain Processes
############################
function destroy {
    if ! ( [ $1 ])	then
		echo -e "${RED}Missing Argument: [dns|ssh]${WHITE}"
		return
    fi
    case "$1" in
		dns)
		  sudo dscacheutil -flushcache;
		  sudo killall -HUP mDNSResponder;
		  echo -e "${BLUE}DNS Cashe Flushed${WHITE}";
		  ;;
		ssh)
		  sudo killall ssh;
		  echo -e "${BLUE}SSH Tunnels Destroyed${WHITE}";
		  ;;
		*)
	  echo -e "${RED}Invalid Argument: [dns|ssh]${WHITE}"
	  return
	  ;;
    esac
}

git_prompt() {
    local branch="$(git symbolic-ref HEAD 2> /dev/null | cut -d'/' -f3-)"
    local branch_truncated="${branch:0:30}"

    if (( ${#branch} > ${#branch_truncated} )); then
        branch="${branch_truncated}..."
    fi

    [ -n "${branch}" ] && echo " (${branch})"
}


#################################
# **END Helper Functions Script**
#################################
