#!/bin/bash
##################################
### Mobile Development Commands ##
##################################



function uh-android {
	if ! ( [ $1 ])	then
	echo "Missing commands USAGE: %s [tools|build]"
	return
    fi
    case "$1" in
		tools)
		  	sh /opt/local/share/java/android-sdk-macosx/tools/android
		  ;;
		deploy)
		   	echo -e "${YELLOW}Preparing To Generate Android APK${WHITE}";
			#Save the users current path
			pushd $REDLINEPROJECT/ionic-project;
			#Check for existing APK File
			if [ -f $REDLINEPROJECT/production/Redline.apk ]; then
				rm $REDLINEPROJECT/production/Redline.apk;
				echo -e "${RED}Overriding Existing APK File${WHITE}";
			fi
			#Build the App
			echo -e "${PURPLE}Generating APK File${WHITE}";
			cordova build --release android;
			#Jarsign and ZipAlign the APK
			echo -e "${BLUE}Preparing APK for Google Play Store${WHITE}";
			jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore $REDLINEPROJECT/resources/auths/ionic/Redline2.0.keystore $REDLINEPROJECT/ionic-project/platforms/android/build/outputs/apk/android-release-unsigned.apk redline;
			zipalign 4 $REDLINEPROJECT/ionic-project/platforms/android/build/outputs/apk/android-release-unsigned.apk $REDLINEPROJECT/production/Redline.apk;
			echo -e "${GREEN}APK Ready at $REDLINEPROJECT/production/ ${WHITE}";
			popd;
		  ;;
		*)
	  echo "Invalid argument."
	  return
	  ;;
    esac
}
