#!/bin/bash
##########################
# DB Connections Tunnel ##
##########################

# This script creates a funtion that is initialize in the commands script to connect to the database tunnel.

##################
# UH DB Congig  ##
##################

SSH_W_OPT="ssh -o ServerAliveInterval=60"
SSH_W_FORWARD="$SSH_W_OPT -f $USER@eris.web.e.uh.edu"

##########################
#### UH DB FUNCTION    ###
##########################

mysql_tunnel(){
	date
	if ! ( [ $1 ] && [ $2 ] )	then
        # Do something
        echo "Missing commands USAGE: %s [start|stop] [datbase]"
        return
	fi

	CCMD=0
	CCMD_PRT=0
	FWRD=""
	case "$2" in
		db1)
			CCMD_PRT="3310:db1.web.e.uh.edu:3306"
			EXEC_CCMD=1
			;;
		db2)
		 	CCMD_PRT="3311:db2.web.e.uh.edu:3306"
			EXEC_CCMD=1
			;;
		alerts)
			CCMD_PRT="3320:production-alerts-cluster-1.cluster-cqzqmiqsh6d3.us-west-2.rds.amazonaws.com:3306"
			EXEC_CCMD=1
			;;
		cloud_db1)
			SSH_W_FORWARD="$SSH_W_OPT -f $USER@34.208.16.90"
			CCMD_PRT="3323:webfarm.cqzqmiqsh6d3.us-west-2.rds.amazonaws.com:3306"
			EXEC_CCMD=1
			;;
		* )
			echo "Nothing to do"
			return
			;;

	esac

	case "$1" in
		start)
			CCMD_TYPE="start"

			CCMD="$SSH_W_FORWARD -L $CCMD_PRT -N"
			KCMD="pkill -fl \"${CCMD}\""

			echo "KILLING existing tunnels for $1"
			echo "pkill -fl \"${CCMD}\""
			pkill -fl "$CCMD"

			echo "STARTING tunnel for $1"
			echo $CCMD
			$CCMD

			;;
		stop)
			CCMD_TYOE="stop"
			CCMD="$SSH_W_FORWARD -L $CCMD_PRT:localhost:3306 -N"
			KCMD="pkill -fl \"${CCMD}\""

			echo "KILLING existing tunnels for $1"
			echo "pkill -fl \"$CCMD\""
			pkill -fl "$CCMD"

			;;
		*)
			echo "missing [start|stop]"
	esac



}
